### ISSUE TITLE
URL e código de barras não são retornados!

### ISSUE THREAD

**Issue by walisoncecilio** [pagarme/pagarme-python#110]
Na resposta do método transaction.create() as propriedades **boleto_url** e **boleto_barcode** não estão sendo retornadas. Esse é o comportamento esperado?

**Comment by iurisilvio** [comment]
No ambiente de homologação acho que é esperado sim. Não é gerado um boleto real nesse caso.

**Comment by walisoncecilio** [comment]
Acho que o ambiente de homologação deveria se comportar do mesmo jeito que o de produção.
O estranho é que ao obter o a transação usando `transaction.find_by_id'`, são retornados as propriedades **boleto_url** e **boleto_barcode** .

OBS: Quando uso `transaction.find_by_id'` logo depois de usar ` transaction.create`, ele não retorna  **boleto_url** e **boleto_barcode**, acho que algum processo roda em backgroud para gerar o boleto.

**Comment by murilohns** [comment]
@walisoncecilio, tudo bem?
ao criar uma transação, você pode enviar o parâmetro `async=false` para que os dados de boleto sejam retornados.

Neste cenário, e em ambiente de testes, os dados dados devem vir dessa forma:

```
boleto_url: "https://pagar.me"
boleto_barcode: "1234 5678"
status: "waiting_payment"
```
