### ISSUE TITLE
Can't create card hash 

### ISSUE THREAD

**Issue by pbassut** [pagarme/pagarme-python#14]
Do I need the JS library to create a cardhash?
I wanted to create an entirely backend app.

If there's no way to do that using this library, is there some other way?
I went over the js script and noticed is merely a post to a pagarme endpoint with some encrypted parameters.
I just wanted to know if there was other ways to accomplish this.

**Comment by mbodock** [comment]
Right now the lib doesn't support.
Here the [link](https://docs.pagar.me/api/#criando-um-cartao) of the proper way to create a credit card.
A PR would be welcome.

**Comment by pbassut** [comment]
So, I was going to make a PR.
But while digging into the source code, I found that I can create a card like this:
```python
>>> c = Card('ak_test_JzSij5kZCYrbRzMHEEnoshitdude', card_number='4018720572598048', expiration_date=1216, holder_name='Patrick B')
>>> c.create()
>>> c.get_data() # this prints the card data
```

**Comment by pbassut** [comment]
What I find a bit cumbersome, though, is the fact that I need to create a card before actually making a transaction. Meaning those are two requests. I'm obligated to do that.
But that's a problem for the pagarme guys.
