### ISSUE TITLE
Should't customer also inherit from AbstractResource?

### ISSUE THREAD

**Issue by pbassut** [pagarme/pagarme-python#15]
Customer is also a Resource from my point of view.
That said, it should inherit from AbstractResource like the others.
It does have a resource url(e.g. "/customer"), it can be created and all that.

Right?

**Comment by mbodock** [comment]
Sure mind open a PR ?

**Comment by pbassut** [comment]
Working on it...

**Comment by victorgama** [comment]
Fixed by 7d177e9d8dbb90226174cf2b433ffd31faff79b5 (:

**Comment by mbodock** [comment]
Without BASE_URL all posts will be to https://api.pagar.me/1/
and so failing.

**Comment by pbassut** [comment]
@victorgama Let me know the next time you will get the changes from my commit and put them in your commit and close my PR because, well, fuck my time. 
Thanks :)
