### ISSUE TITLE
Missing pagarme-python as requirements

### ISSUE THREAD

**Issue by pbassut** [pagarme/pagarme-python#16]
It's neither on requirements.txt or requirements-dev.txt

**Comment by mbodock** [comment]
what is missing ?

**Comment by pbassut** [comment]
For testing the pagarme package is needed. It's not on requirements-dev.

**Comment by mbodock** [comment]
No it's not.
When you test you should clone the repository a run inside your cloned directory. So you can test your local changes in the lib.

**Comment by pbassut** [comment]
Makes sense. I didn't think for a minute. Sorry
