### ISSUE TITLE
JSON parsing error after request in python 3

### ISSUE THREAD

**Issue by hugollm** [pagarme/pagarme-python#24]
When testing on python3, every request I try to make greets me with an error:

```
Traceback (most recent call last):
  File "script.py", line 9, in <module>
    transaction.charge()
  File "/home/hugollm/.virtualenvs/pagarme/lib/python3.4/site-packages/pagarme/transaction.py", line 56, in charge
    self.error(pagarme_response.content)
  File "/home/hugollm/.virtualenvs/pagarme/lib/python3.4/site-packages/pagarme/transaction.py", line 44, in error
    data = json.loads(response)
  File "/usr/lib/python3.4/json/__init__.py", line 312, in loads
    s.__class__.__name__))
TypeError: the JSON object must be str, not 'bytes'
```

It seems to be happening on unsucessful requests (not 200 response). I wasn't able to test on a successful one, though. Tested with the following code:

```
from pagarme import Pagarme

pagarme = Pagarme('ak_test_***')
transaction = pagarme.start_transaction(
    amount=10,
    card_hash='***==',
    payment_method='credit_card'
)
transaction.charge()
```

Used `***` to omit sensitive information.

**Comment by mbodock** [comment]
I believe **pgferretti** was trying to fix that on this (PR)[https://github.com/pagarme/pagarme-python/pull/12]

I'll fix it, as soon as i can.

**Comment by mbodock** [comment]
Hi @hugollm!

I believe i have fixed. Do you mind confirm that for me?
So far it is in my repository.
To install just do: `pip install git+https://github.com/mbodock/pagarme-python@fix-24`
Regards

**Comment by hugollm** [comment]
Awesome! But I'm afraid I won't have the time to look into it. I ended up not using the library.
