### ISSUE TITLE
New authentication schema

### ISSUE THREAD

**Issue by greenboxal** [pagarme/pagarme-python#3]
It's not in the docs but using `api_key` and `encryption_key` fields in the body is deprecated.

The correct way is to send the API Key with HTTP basic authentication as the username. Also, the password must be `x`.

**Comment by mbodock** [comment]
You guys should make the docs opensource.
And of course i'll change when i have some time.

**Comment by greenboxal** [comment]
I was talking with Leroy about it. I've done it in the morning: https://github.com/pagarme/docs.pagar.me

**Comment by murilohns** [comment]
Hi @greenboxal, may i close this issue?
