### ISSUE TITLE
Pypi's metadata

### ISSUE THREAD

**Issue by henriquekano** [pagarme/pagarme-python#33]
The pypi version [(this)](https://pypi.python.org/pypi/pagarme-python/2.1.1) doesn't seem to work with subscription metadata:
```python
sub = Subscription(
            api_key='API_KEY",
            plan_id=87509,
            card_id='card_cixm63x0l00krin6d6tmhrnvh',
            customer=customer,
            metadata={
                "object": {
                    "sdfsdfsd": "algo"
                }
            }
        )
sub.create()
```

**Comment by mbodock** [comment]
That's right. The `metada` was fixed  Jul 14, 2016, our last release was  on Oct 8, 2015.

@lerrua how about a new release ?

**Comment by lerrua** [comment]
@mbodock sounds good, i'll release 2.1.2 version. 👍

**Comment by rodrigoPgSup** [comment]
Hey @lerrua , how are you? 

I was wondering if only you has the rights to publish new releases, and you if would be willing to share this great power with us from Pagar.Me? What do you think? 

See ya 👍

**Comment by lerrua** [comment]
@rodrigoPgSup sure, send me an email or call me at hangout please. (ip.leroy @ gmail)

**Comment by rodrigoPgSup** [comment]
Awesome @lerrua , we'll be in touch ;)

**Comment by lerrua** [comment]
@mbodock @rodrigoPgSup version 2.1.2 released today 👍

**Comment by rodrigoPgSup** [comment]
Hey @lerrua , sweet! We'll open a PR soon with new features as well.
