### ISSUE TITLE
Missing requirements.txt when installing from PyPi (pip)

### ISSUE THREAD

**Issue by hails** [pagarme/pagarme-python#8]
When calling `pip install pagarme-python`, it gives the following output:
```
Traceback (most recent call last):
  File "<string>", line 20, in <module>
  File "/tmp/pip-build-o69jyrm9/pagarme-python/setup.py", line 5, in <module>
    requires = [i.strip() for i in open("requirements.txt").readlines()]
FileNotFoundError: [Errno 2] No such file or directory: 'requirements.txt'
```

And looking into the package [pagarme-python-2.0.0.tar.gz](https://pypi.python.org/packages/source/p/pagarme-python/pagarme-python-2.0.0.tar.gz#md5=37c32a2bd4f3e46e006cc1d0f82379a2) , there's no file named `requirements.txt`.

**Comment by lerrua** [comment]
@hails now you can try install with `pip install pagarme-python`

**Comment by hails** [comment]
@lerrua It's working now. Very thanks!
