### ISSUE TITLE
Generate Card Hash method

### ISSUE THREAD

**Issue by Nixsm** [pagarme/pagarme-python#80]
Hey, I've implemented the card_hash method in my python project, but I'm not sure where to implement it in the library, could someone please enlighten me?

**Comment by murilohns** [comment]
hello @Nixsm , not sure, but i think u can insert it into https://github.com/pagarme/pagarme-python/blob/master/pagarme/card.py

**Comment by felquis** [comment]
@Nixsm could you send a PR?
