### ISSUE TITLE
Unable to identify errors (or any other request status_code)

### ISSUE THREAD

**Issue by cnadm** [pagarme/pagarme-python#81]
Hi guys,

Correct me if I'm wrong, but in the way the API is coded now there is no way to know what was the HTTP response code. Let`s say I do the following request:
```
pagarme.authentication_key('...')
subscription = pagarme.subscription.create({...})
```

If everything goes well and the subscription is registered, this approach has no problems. However, if something goes wrong on `pagarme.subscription.create`, than the following happens:

- `pagarme.subscription.create` calls `handler_request.post`
- `handler_request.post` calls `pagarme.resources.handler_request.validate_response`
- `pagarme.resources.handler_request.validate_response` calls `pagarme.resources.handler_request.error`
- `pagarme.resources.handler_request.error` simply returns 
the error data array

In this process, we completely miss the status_code. This means that, once `subscription = pagarme.subscription.create` has gone wrong, there is no `if subscription.status_code == 400` or some `try: ... except: PagarmeException e: ...` that we can use.

The only current way I see to know if the response is an error would be some odd array format testing, like: `if 'message' in subscription and 'parameter_name' in subscription and 'type' in subscription: # we have an error`.

Please let me know if there is another way that I did not see or if you intend to fix this.
I used `pagarme.subscription.create` in the example, but as far as I know this problem affects any other methods having HTTP calls as they go by `pagarme.resources.handler_request.validate_response`.

**Comment by rserro** [comment]
Hi,

I did the post above. Currently using this *unpretty* workaround:
```
class PagarMeErrorException(Exception):
    def __init__(self, message, errors):
        super().__init__(message)
        self.errors = errors


class PagarMeErrorsHelper:
    @staticmethod
    def check_errors(res_json):
        if isinstance(res_json, list) and len(res_json) > 0 and len(res_json[0]) == 3 and \
                'message' in res_json[0] and 'parameter_name' in res_json[0] and 'type' in res_json[0]:
            raise PagarMeErrorException("Pagar.me errors occurred.", res_json)
        return res_json


# One way of using it would be this:
try:
    pagarme.authentication_key('...')
    subscription = pagarme.subscription.create({...})
    PagarMeErrorsHelper.check_errors(subscription)
except PagarMeErrorException as e:
    # Do your stuff.
    # Errors list are stored in e.errors
    pass
```

**Comment by murilohns** [comment]
Hi @cingulo, can u see if #82 solves the problem?

**Comment by rserro** [comment]
@murilohns It does but it misses the errors list as it is passed as the exception message param. I think it would be better to use something like `PagarMeErrorException` above, so that we can accomplish two things: 1 - Know an error occurred. 2 - Know details about the errors. The PR #82 only accounts for item 1.

**Comment by murilohns** [comment]
hello @rserro, with #82, i used this payload:

```
params = {
  'amount': '10000',
  'payment_method': 'credit_card',
  'card_id': 'card_cj8eelm4100btyb6e444vnaho',
  'customer': {
    'email': 'daenerys.targaryen@gmail.com',
    'name': 'Daenerys Targaryen',
    **'document_number': '11111111111111111111111111',**
    'address': {
        **'zipcode': '12345692163',**
        'neighborhood': 'Dragon Village',
        'street': 'Rua Drogon',
        'street_number': '240'
     },
    'phone': {
      	'number': '987654321',
        'ddd': '11'
    }
  }
}
```
And the it throws:

`Exception: [{u'message': u'n\xfamero do documento n\xe3o \xe9 um CPF ou CNPJ v\xe1lido', u'type': u'invalid_parameter', u'parameter_name': u'customer[document_number]'}, {u'message': u'CEP n\xe3o encontrado', u'type': u'invalid_parameter', u'parameter_name': u'customer[address][zipcode]'}]`

**Comment by rserro** [comment]
@murilohns I think your right, I could access the list through:

```
try:
    # pagarme call that raises exception
except Exception e:
    e.args # the list will be here
```

Thanks

**Comment by murilohns** [comment]
hello @rserro, @cingulo may i deploy #82?

**Comment by rserro** [comment]
@murilohns OK for us (speaking on behalf of @cingulo as well).
