### ISSUE TITLE
Migração para o protocolo TLS 1.2

### ISSUE THREAD

**Issue by thiagoreis** [pagarme/pagarme-python#87]
Recebi um e-mail sobre a "Migração para o protocolo TLS 1.2" e gostaria de saber se a biblioteca terá suporte para esse protocolo?

Grato.

**Comment by jonatasmaxi** [comment]
Olá @thiagoreis tudo bom?

Meu nome é Jonatas e faço parte da equipe de suporte técnico do Pagar.me. 

Para que  as suas requisições continuem ocorrendo com sucesso aqui para o Pagar.me você precisa verificar qual a versão do TLS de seu servidor visto que o python usa o OpenSSL fornecida pelo sistema. O TLS 1.2 precisa da versão 1.0.1c OpenSSL ou superior.

### Testando sua conexão com TLS 1.2.

    Baixe [esse arquivo](https://github.com/pagarme/TLS-update/blob/master/Python/tls-example.py) em seu servidor.

    Execute o arquivo com o comando python tls-example.py
        Em caso de sucesso, a seguinte mensagem será retornada:

    Sucesso: sua conexão com a Pagar.me está utilizando o protocolo TLS 1.2.

        Em caso de falha, a seguinte mensagem será exibida:

    Sua versão SSL é XXX
    Sua versão deve ser superior à 1.0.1c

**Comment by murilohns** [comment]
Resolvida em https://github.com/pagarme/pagarme-php/issues/262
