### ISSUE TITLE
Validar um postback

### ISSUE THREAD

**Issue by Cayke** [pagarme/pagarme-python#88]
Creio que faltou uma classe/metodo para validar os postbacks enviados pela pagar.me
Segue documetacao sobre assunto a que me refiro.
https://docs.pagar.me/v2017-08-28/reference#validando-um-postback

**Comment by leonardo-barbosa** [comment]
Fala @Cayke , tudo certo?

Realmente ainda não temos essa funcionalidade implementada, porém já estou trabalhando nisso no PR #89 .

Como o build está quebrado, ainda tenho que corrigi-lo para fundir na `master`.

Qualquer dúvida, é só falar!

Abraços.

**Comment by leonardo-barbosa** [comment]
Resolvido no PR #89 .

**Comment by arturodrigues78** [comment]
Boa tarde, @leonardo-barbosa , você tem algum exemplo de código de retorno do postback_url? não faço ideia de como pegar o status retornado de uma transação, se tiver vai me ajudar muito...

**Comment by victorqueirozlife** [comment]
Tenho a mesma dúvida do @arturodrigues78 você conseguiu amigo?

**Comment by arturodrigues78** [comment]
consegui sim, me chama no whatsapp (21)988342898

Em sex., 16 de out. de 2020 às 03:45, victorqueirozlife <
notifications@github.com> escreveu:
