### ISSUE TITLE
Testes quebrando

### ISSUE THREAD

**Issue by murilohns** [pagarme/pagarme-python#90]
Corrigir os testes para que eles passem a funcionar corretamente.

Atualmente sleeps são utilizados, mas em pesquisas notei que a lib requests já trabalha sincronamente, não sendo necessário o uso dessa função.

**Comment by renzon** [comment]
Eu achei que os sleeps serviam para o sandbox não achar que está sofrendo um a ataque DoS.

**Comment by iurisilvio** [comment]
Os sleeps são porque o pagarme demora pra atualizar as informações. Acontecem coisas assincronas no servidor. Foi o que eu descobri no #106.

Essa issue está resolvida.
