### ISSUE TITLE
Count não presente nos métodos de find_all()

### ISSUE THREAD

**Issue by jonatasmaxi** [pagarme/pagarme-python#96]
Implementação dos parâmetros count e page nos métdos find_all do SDK.

**Comment by murilohns** [comment]
esses parâmetros podem ser enviados dentro da função.
ex:
```python
pagarme.transaction.find_by({
    "count": 100,
    "page": 2
})
```

**Comment by murilohns** [comment]
Não acho uma boa ideia.

1. `find_by` resolve seu problema, que é buscar algo enviando parâmetros na busca
2. alterar o nome da função iria quebrar a interface da biblioteca
